version: '3.8'

services:
  # PostgreSQL service
  # postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: my_database
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app_network

  # MinIO service
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

# Named volumes for persistent data storage
volumes:
  postgres_data:
  minio_data:

# Define networks
networks:
  app_network:
    driver: bridge
